// <auto-generated />
using System;
using CarSales.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarSales.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210917083002_changeColumnNames")]
    partial class changeColumnNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarSales.Domain.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(15)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("FinishedSale")
                        .HasColumnType("DateTime");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("Price")
                        .HasColumnType("Int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("StartedSale")
                        .HasColumnType("DateTime");

                    b.Property<string>("VinCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(17)");

                    b.HasKey("Id")
                        .HasName("pk_CarId");

                    b.HasIndex("ClientId");

                    b.HasIndex("VinCode")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarSales.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DateTime");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("FirstName")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(11)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("NVARCHAR(30)");

                    b.HasKey("Id")
                        .HasName("pk_ClientId");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarSales.Domain.Models.Car", b =>
                {
                    b.HasOne("CarSales.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
